[cmd_duration]
prefix = ""

[battery]
disabled = true

[dotnet]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[haskell]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[hg_branch]
disabled = true

[package]
disabled = true

[php]
disabled = true

[singularity]
disabled = true

[terraform]
disabled = true
